/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinEvent */

#ifndef _Included_org_unclesniper_winwin_WinEvent
#define _Included_org_unclesniper_winwin_WinEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_WinEvent_CHILDID_SELF
#define org_unclesniper_winwin_WinEvent_CHILDID_SELF 9223372036854775807i64
#ifdef __cplusplus
}
#endif
#endif
