/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinHook_LowLevelHotkey */

#ifndef _Included_org_unclesniper_winwin_WinHook_LowLevelHotkey
#define _Included_org_unclesniper_winwin_WinHook_LowLevelHotkey
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
