/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_Hotkey */

#ifndef _Included_org_unclesniper_winwin_Hotkey
#define _Included_org_unclesniper_winwin_Hotkey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_unclesniper_winwin_Hotkey
 * Method:    unregisterHotKeyImpl
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_Hotkey_unregisterHotKeyImpl
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_unclesniper_winwin_Hotkey
 * Method:    registerHotKeyImpl
 * Signature: (JIIS)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_Hotkey_registerHotKeyImpl
  (JNIEnv *, jclass, jlong, jint, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
