/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_HWnd_ShowWindow */

#ifndef _Included_org_unclesniper_winwin_HWnd_ShowWindow
#define _Included_org_unclesniper_winwin_HWnd_ShowWindow
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
