/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WndClassEx */

#ifndef _Included_org_unclesniper_winwin_WndClassEx
#define _Included_org_unclesniper_winwin_WndClassEx
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_WndClassEx_CS_BYTEALIGNCLIENT
#define org_unclesniper_winwin_WndClassEx_CS_BYTEALIGNCLIENT 4096L
#undef org_unclesniper_winwin_WndClassEx_CS_BYTEALIGNWINDOW
#define org_unclesniper_winwin_WndClassEx_CS_BYTEALIGNWINDOW 8192L
#undef org_unclesniper_winwin_WndClassEx_CS_CLASSDC
#define org_unclesniper_winwin_WndClassEx_CS_CLASSDC 64L
#undef org_unclesniper_winwin_WndClassEx_CS_DBLCLKS
#define org_unclesniper_winwin_WndClassEx_CS_DBLCLKS 8L
#undef org_unclesniper_winwin_WndClassEx_CS_DROPSHADOW
#define org_unclesniper_winwin_WndClassEx_CS_DROPSHADOW 131072L
#undef org_unclesniper_winwin_WndClassEx_CS_GLOBALCLASS
#define org_unclesniper_winwin_WndClassEx_CS_GLOBALCLASS 16384L
#undef org_unclesniper_winwin_WndClassEx_CS_HREDRAW
#define org_unclesniper_winwin_WndClassEx_CS_HREDRAW 2L
#undef org_unclesniper_winwin_WndClassEx_CS_NOCLOSE
#define org_unclesniper_winwin_WndClassEx_CS_NOCLOSE 512L
#undef org_unclesniper_winwin_WndClassEx_CS_OWNDC
#define org_unclesniper_winwin_WndClassEx_CS_OWNDC 32L
#undef org_unclesniper_winwin_WndClassEx_CS_PARENTDC
#define org_unclesniper_winwin_WndClassEx_CS_PARENTDC 128L
#undef org_unclesniper_winwin_WndClassEx_CS_SAVEBITS
#define org_unclesniper_winwin_WndClassEx_CS_SAVEBITS 2048L
#undef org_unclesniper_winwin_WndClassEx_CS_VREDRAW
#define org_unclesniper_winwin_WndClassEx_CS_VREDRAW 1L
/*
 * Class:     org_unclesniper_winwin_WndClassEx
 * Method:    registerClassExImpl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_WndClassEx_registerClassExImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
