/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_HWnd */

#ifndef _Included_org_unclesniper_winwin_HWnd
#define _Included_org_unclesniper_winwin_HWnd
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_HWnd_CW_USEDEFAULT
#define org_unclesniper_winwin_HWnd_CW_USEDEFAULT -2147483648L
#undef org_unclesniper_winwin_HWnd_SYMBOLIC_HWND_MESSAGE
#define org_unclesniper_winwin_HWnd_SYMBOLIC_HWND_MESSAGE -9223372036854775808i64
#undef org_unclesniper_winwin_HWnd_WS_EX_ACCEPTFILES
#define org_unclesniper_winwin_HWnd_WS_EX_ACCEPTFILES 16L
#undef org_unclesniper_winwin_HWnd_WS_EX_APPWINDOW
#define org_unclesniper_winwin_HWnd_WS_EX_APPWINDOW 262144L
#undef org_unclesniper_winwin_HWnd_WS_EX_CLIENTEDGE
#define org_unclesniper_winwin_HWnd_WS_EX_CLIENTEDGE 512L
#undef org_unclesniper_winwin_HWnd_WS_EX_COMPOSITED
#define org_unclesniper_winwin_HWnd_WS_EX_COMPOSITED 33554432L
#undef org_unclesniper_winwin_HWnd_WS_EX_CONTEXTHELP
#define org_unclesniper_winwin_HWnd_WS_EX_CONTEXTHELP 1024L
#undef org_unclesniper_winwin_HWnd_WS_EX_CONTROLPARENT
#define org_unclesniper_winwin_HWnd_WS_EX_CONTROLPARENT 65536L
#undef org_unclesniper_winwin_HWnd_WS_EX_DLGMODALFRAME
#define org_unclesniper_winwin_HWnd_WS_EX_DLGMODALFRAME 1L
#undef org_unclesniper_winwin_HWnd_WS_EX_LAYERED
#define org_unclesniper_winwin_HWnd_WS_EX_LAYERED 524288L
#undef org_unclesniper_winwin_HWnd_WS_EX_LAYOUTRTL
#define org_unclesniper_winwin_HWnd_WS_EX_LAYOUTRTL 4194304L
#undef org_unclesniper_winwin_HWnd_WS_EX_LEFT
#define org_unclesniper_winwin_HWnd_WS_EX_LEFT 0L
#undef org_unclesniper_winwin_HWnd_WS_EX_LEFTSCROLLBAR
#define org_unclesniper_winwin_HWnd_WS_EX_LEFTSCROLLBAR 16384L
#undef org_unclesniper_winwin_HWnd_WS_EX_LTRREADING
#define org_unclesniper_winwin_HWnd_WS_EX_LTRREADING 0L
#undef org_unclesniper_winwin_HWnd_WS_EX_MDICHILD
#define org_unclesniper_winwin_HWnd_WS_EX_MDICHILD 64L
#undef org_unclesniper_winwin_HWnd_WS_EX_NOACTIVATE
#define org_unclesniper_winwin_HWnd_WS_EX_NOACTIVATE 134217728L
#undef org_unclesniper_winwin_HWnd_WS_EX_NOINHERITLAYOUT
#define org_unclesniper_winwin_HWnd_WS_EX_NOINHERITLAYOUT 1048576L
#undef org_unclesniper_winwin_HWnd_WS_EX_NOPARENTNOTIFY
#define org_unclesniper_winwin_HWnd_WS_EX_NOPARENTNOTIFY 4L
#undef org_unclesniper_winwin_HWnd_WS_EX_NOREDIRECTIONBITMAP
#define org_unclesniper_winwin_HWnd_WS_EX_NOREDIRECTIONBITMAP 2097152L
#undef org_unclesniper_winwin_HWnd_WS_EX_RIGHT
#define org_unclesniper_winwin_HWnd_WS_EX_RIGHT 4096L
#undef org_unclesniper_winwin_HWnd_WS_EX_RIGHTSCROLLBAR
#define org_unclesniper_winwin_HWnd_WS_EX_RIGHTSCROLLBAR 0L
#undef org_unclesniper_winwin_HWnd_WS_EX_RTLREADING
#define org_unclesniper_winwin_HWnd_WS_EX_RTLREADING 8192L
#undef org_unclesniper_winwin_HWnd_WS_EX_STATICEDGE
#define org_unclesniper_winwin_HWnd_WS_EX_STATICEDGE 131072L
#undef org_unclesniper_winwin_HWnd_WS_EX_TOOLWINDOW
#define org_unclesniper_winwin_HWnd_WS_EX_TOOLWINDOW 128L
#undef org_unclesniper_winwin_HWnd_WS_EX_TOPMOST
#define org_unclesniper_winwin_HWnd_WS_EX_TOPMOST 8L
#undef org_unclesniper_winwin_HWnd_WS_EX_TRANSPARENT
#define org_unclesniper_winwin_HWnd_WS_EX_TRANSPARENT 32L
#undef org_unclesniper_winwin_HWnd_WS_EX_WINDOWEDGE
#define org_unclesniper_winwin_HWnd_WS_EX_WINDOWEDGE 256L
#undef org_unclesniper_winwin_HWnd_WS_EX_OVERLAPPEDWINDOW
#define org_unclesniper_winwin_HWnd_WS_EX_OVERLAPPEDWINDOW 768L
#undef org_unclesniper_winwin_HWnd_WS_EX_PALETTEWINDOW
#define org_unclesniper_winwin_HWnd_WS_EX_PALETTEWINDOW 392L
#undef org_unclesniper_winwin_HWnd_WS_BORDER
#define org_unclesniper_winwin_HWnd_WS_BORDER 8388608L
#undef org_unclesniper_winwin_HWnd_WS_CAPTION
#define org_unclesniper_winwin_HWnd_WS_CAPTION 12582912L
#undef org_unclesniper_winwin_HWnd_WS_CHILD
#define org_unclesniper_winwin_HWnd_WS_CHILD 1073741824L
#undef org_unclesniper_winwin_HWnd_WS_CHILDWINDOW
#define org_unclesniper_winwin_HWnd_WS_CHILDWINDOW 1073741824L
#undef org_unclesniper_winwin_HWnd_WS_CLIPCHILDREN
#define org_unclesniper_winwin_HWnd_WS_CLIPCHILDREN 33554432L
#undef org_unclesniper_winwin_HWnd_WS_CLIPSIBLINGS
#define org_unclesniper_winwin_HWnd_WS_CLIPSIBLINGS 67108864L
#undef org_unclesniper_winwin_HWnd_WS_DISABLED
#define org_unclesniper_winwin_HWnd_WS_DISABLED 134217728L
#undef org_unclesniper_winwin_HWnd_WS_DLGFRAME
#define org_unclesniper_winwin_HWnd_WS_DLGFRAME 4194304L
#undef org_unclesniper_winwin_HWnd_WS_GROUP
#define org_unclesniper_winwin_HWnd_WS_GROUP 131072L
#undef org_unclesniper_winwin_HWnd_WS_HSCROLL
#define org_unclesniper_winwin_HWnd_WS_HSCROLL 1048576L
#undef org_unclesniper_winwin_HWnd_WS_ICONIC
#define org_unclesniper_winwin_HWnd_WS_ICONIC 536870912L
#undef org_unclesniper_winwin_HWnd_WS_MAXIMIZE
#define org_unclesniper_winwin_HWnd_WS_MAXIMIZE 16777216L
#undef org_unclesniper_winwin_HWnd_WS_MAXIMIZEBOX
#define org_unclesniper_winwin_HWnd_WS_MAXIMIZEBOX 65536L
#undef org_unclesniper_winwin_HWnd_WS_MINIMIZE
#define org_unclesniper_winwin_HWnd_WS_MINIMIZE 536870912L
#undef org_unclesniper_winwin_HWnd_WS_MINIMIZEBOX
#define org_unclesniper_winwin_HWnd_WS_MINIMIZEBOX 131072L
#undef org_unclesniper_winwin_HWnd_WS_OVERLAPPED
#define org_unclesniper_winwin_HWnd_WS_OVERLAPPED 0L
#undef org_unclesniper_winwin_HWnd_WS_POPUP
#define org_unclesniper_winwin_HWnd_WS_POPUP -2147483648L
#undef org_unclesniper_winwin_HWnd_WS_SIZEBOX
#define org_unclesniper_winwin_HWnd_WS_SIZEBOX 262144L
#undef org_unclesniper_winwin_HWnd_WS_SYSMENU
#define org_unclesniper_winwin_HWnd_WS_SYSMENU 524288L
#undef org_unclesniper_winwin_HWnd_WS_TABSTOP
#define org_unclesniper_winwin_HWnd_WS_TABSTOP 65536L
#undef org_unclesniper_winwin_HWnd_WS_THICKFRAME
#define org_unclesniper_winwin_HWnd_WS_THICKFRAME 262144L
#undef org_unclesniper_winwin_HWnd_WS_TILED
#define org_unclesniper_winwin_HWnd_WS_TILED 0L
#undef org_unclesniper_winwin_HWnd_WS_VISIBLE
#define org_unclesniper_winwin_HWnd_WS_VISIBLE 268435456L
#undef org_unclesniper_winwin_HWnd_WS_VSCROLL
#define org_unclesniper_winwin_HWnd_WS_VSCROLL 2097152L
#undef org_unclesniper_winwin_HWnd_WS_OVERLAPPEDWINDOW
#define org_unclesniper_winwin_HWnd_WS_OVERLAPPEDWINDOW 13565952L
#undef org_unclesniper_winwin_HWnd_WS_POPUPWINDOW
#define org_unclesniper_winwin_HWnd_WS_POPUPWINDOW -2138570752L
#undef org_unclesniper_winwin_HWnd_WS_TILEDWINDOW
#define org_unclesniper_winwin_HWnd_WS_TILEDWINDOW 13565952L
/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    closeWindow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_HWnd_closeWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    showWindowImpl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_showWindowImpl
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    getWindowTextImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_HWnd_getWindowTextImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    getClassNameImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_HWnd_getClassNameImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    isWindowVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_isWindowVisible
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    isIconic
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_isIconic
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    isZoomed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_isZoomed
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    getWindowThreadId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_getWindowThreadId
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    getWindowProcessId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_getWindowProcessId
  (JNIEnv *, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    createWindowExByClassAtom
 * Signature: (IILjava/lang/String;IIIIIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_createWindowExByClassAtom
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint, jint, jint, jint, jlong, jlong);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    createWindowExByClassName
 * Signature: (ILjava/lang/String;Ljava/lang/String;IIIIIJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_createWindowExByClassName
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jint, jint, jint, jlong, jlong);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    enumWindowsImpl
 * Signature: (Lorg/unclesniper/winwin/WndEnumProc;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_enumWindowsImpl
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    getForegroundWindowImpl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_getForegroundWindowImpl
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    setForegroundWindowImpl
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_HWnd_setForegroundWindowImpl
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    findWindowImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_HWnd_findWindowImpl
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
