/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinHook */

#ifndef _Included_org_unclesniper_winwin_WinHook
#define _Included_org_unclesniper_winwin_WinHook
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_WinHook_WH_KEYBOARD_LL
#define org_unclesniper_winwin_WinHook_WH_KEYBOARD_LL 1L
#undef org_unclesniper_winwin_WinHook_WH_CALLWNDPROCRET
#define org_unclesniper_winwin_WinHook_WH_CALLWNDPROCRET 2L
#undef org_unclesniper_winwin_WinHook_WH_ALL
#define org_unclesniper_winwin_WinHook_WH_ALL 3L
/*
 * Class:     org_unclesniper_winwin_WinHook
 * Method:    doYaThang
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_WinHook_doYaThang
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_unclesniper_winwin_WinHook
 * Method:    sendStopMessage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_WinHook_sendStopMessage
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinHook
 * Method:    registerLowLevelHotKeyImpl
 * Signature: (JIIS)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_WinHook_registerLowLevelHotKeyImpl
  (JNIEnv *, jclass, jlong, jint, jint, jshort);

/*
 * Class:     org_unclesniper_winwin_WinHook
 * Method:    unregisterLowLevelHotKeyImpl
 * Signature: (IS)Z
 */
JNIEXPORT jboolean JNICALL Java_org_unclesniper_winwin_WinHook_unregisterLowLevelHotKeyImpl
  (JNIEnv *, jclass, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
