/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinHook_HookThread */

#ifndef _Included_org_unclesniper_winwin_WinHook_HookThread
#define _Included_org_unclesniper_winwin_WinHook_HookThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_WinHook_HookThread_MIN_PRIORITY
#define org_unclesniper_winwin_WinHook_HookThread_MIN_PRIORITY 1L
#undef org_unclesniper_winwin_WinHook_HookThread_NORM_PRIORITY
#define org_unclesniper_winwin_WinHook_HookThread_NORM_PRIORITY 5L
#undef org_unclesniper_winwin_WinHook_HookThread_MAX_PRIORITY
#define org_unclesniper_winwin_WinHook_HookThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
