/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_Hotkey_KeyKey */

#ifndef _Included_org_unclesniper_winwin_Hotkey_KeyKey
#define _Included_org_unclesniper_winwin_Hotkey_KeyKey
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
