/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_HWinEventHook_ObjID */

#ifndef _Included_org_unclesniper_winwin_HWinEventHook_ObjID
#define _Included_org_unclesniper_winwin_HWinEventHook_ObjID
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
