/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_DefWindowProc */

#ifndef _Included_org_unclesniper_winwin_DefWindowProc
#define _Included_org_unclesniper_winwin_DefWindowProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmDestroy
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmDestroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmClose
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmClose
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmActivateApp
 * Signature: (Lorg/unclesniper/winwin/HWnd;Z)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmActivateApp
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmCancelMode
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmCancelMode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmChildActivate
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmChildActivate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmEnable
 * Signature: (Lorg/unclesniper/winwin/HWnd;Z)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmEnable
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmEnterSizeMove
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmEnterSizeMove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmExitSizeMove
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmExitSizeMove
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmGetIconImpl
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmGetIconImpl
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmMove
 * Signature: (Lorg/unclesniper/winwin/HWnd;II)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmMove
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
