/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinAPI */

#ifndef _Included_org_unclesniper_winwin_WinAPI
#define _Included_org_unclesniper_winwin_WinAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_unclesniper_winwin_WinAPI_COLOR_3DDKSHADOW
#define org_unclesniper_winwin_WinAPI_COLOR_3DDKSHADOW 21L
#undef org_unclesniper_winwin_WinAPI_COLOR_3DFACE
#define org_unclesniper_winwin_WinAPI_COLOR_3DFACE 15L
#undef org_unclesniper_winwin_WinAPI_COLOR_3DHIGHLIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_3DHIGHLIGHT 20L
#undef org_unclesniper_winwin_WinAPI_COLOR_3DHILIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_3DHILIGHT 20L
#undef org_unclesniper_winwin_WinAPI_COLOR_3DLIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_3DLIGHT 22L
#undef org_unclesniper_winwin_WinAPI_COLOR_3DSHADOW
#define org_unclesniper_winwin_WinAPI_COLOR_3DSHADOW 16L
#undef org_unclesniper_winwin_WinAPI_COLOR_ACTIVEBORDER
#define org_unclesniper_winwin_WinAPI_COLOR_ACTIVEBORDER 10L
#undef org_unclesniper_winwin_WinAPI_COLOR_ACTIVECAPTION
#define org_unclesniper_winwin_WinAPI_COLOR_ACTIVECAPTION 2L
#undef org_unclesniper_winwin_WinAPI_COLOR_APPWORKSPACE
#define org_unclesniper_winwin_WinAPI_COLOR_APPWORKSPACE 12L
#undef org_unclesniper_winwin_WinAPI_COLOR_BACKGROUND
#define org_unclesniper_winwin_WinAPI_COLOR_BACKGROUND 1L
#undef org_unclesniper_winwin_WinAPI_COLOR_BTNFACE
#define org_unclesniper_winwin_WinAPI_COLOR_BTNFACE 15L
#undef org_unclesniper_winwin_WinAPI_COLOR_BTNHIGHLIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_BTNHIGHLIGHT 20L
#undef org_unclesniper_winwin_WinAPI_COLOR_BTNHILIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_BTNHILIGHT 20L
#undef org_unclesniper_winwin_WinAPI_COLOR_BTNSHADOW
#define org_unclesniper_winwin_WinAPI_COLOR_BTNSHADOW 16L
#undef org_unclesniper_winwin_WinAPI_COLOR_BTNTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_BTNTEXT 18L
#undef org_unclesniper_winwin_WinAPI_COLOR_CAPTIONTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_CAPTIONTEXT 9L
#undef org_unclesniper_winwin_WinAPI_COLOR_DESKTOP
#define org_unclesniper_winwin_WinAPI_COLOR_DESKTOP 1L
#undef org_unclesniper_winwin_WinAPI_COLOR_GRADIENTACTIVECAPTION
#define org_unclesniper_winwin_WinAPI_COLOR_GRADIENTACTIVECAPTION 27L
#undef org_unclesniper_winwin_WinAPI_COLOR_GRADIENTINACTIVECAPTION
#define org_unclesniper_winwin_WinAPI_COLOR_GRADIENTINACTIVECAPTION 28L
#undef org_unclesniper_winwin_WinAPI_COLOR_GRAYTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_GRAYTEXT 17L
#undef org_unclesniper_winwin_WinAPI_COLOR_HIGHLIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_HIGHLIGHT 13L
#undef org_unclesniper_winwin_WinAPI_COLOR_HIGHLIGHTTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_HIGHLIGHTTEXT 14L
#undef org_unclesniper_winwin_WinAPI_COLOR_HOTLIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_HOTLIGHT 26L
#undef org_unclesniper_winwin_WinAPI_COLOR_INACTIVEBORDER
#define org_unclesniper_winwin_WinAPI_COLOR_INACTIVEBORDER 11L
#undef org_unclesniper_winwin_WinAPI_COLOR_INACTIVECAPTION
#define org_unclesniper_winwin_WinAPI_COLOR_INACTIVECAPTION 3L
#undef org_unclesniper_winwin_WinAPI_COLOR_INACTIVECAPTIONTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_INACTIVECAPTIONTEXT 19L
#undef org_unclesniper_winwin_WinAPI_COLOR_INFOBK
#define org_unclesniper_winwin_WinAPI_COLOR_INFOBK 24L
#undef org_unclesniper_winwin_WinAPI_COLOR_INFOTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_INFOTEXT 23L
#undef org_unclesniper_winwin_WinAPI_COLOR_MENU
#define org_unclesniper_winwin_WinAPI_COLOR_MENU 4L
#undef org_unclesniper_winwin_WinAPI_COLOR_MENUHILIGHT
#define org_unclesniper_winwin_WinAPI_COLOR_MENUHILIGHT 29L
#undef org_unclesniper_winwin_WinAPI_COLOR_MENUBAR
#define org_unclesniper_winwin_WinAPI_COLOR_MENUBAR 30L
#undef org_unclesniper_winwin_WinAPI_COLOR_MENUTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_MENUTEXT 7L
#undef org_unclesniper_winwin_WinAPI_COLOR_SCROLLBAR
#define org_unclesniper_winwin_WinAPI_COLOR_SCROLLBAR 0L
#undef org_unclesniper_winwin_WinAPI_COLOR_WINDOW
#define org_unclesniper_winwin_WinAPI_COLOR_WINDOW 5L
#undef org_unclesniper_winwin_WinAPI_COLOR_WINDOWFRAME
#define org_unclesniper_winwin_WinAPI_COLOR_WINDOWFRAME 6L
#undef org_unclesniper_winwin_WinAPI_COLOR_WINDOWTEXT
#define org_unclesniper_winwin_WinAPI_COLOR_WINDOWTEXT 8L
#undef org_unclesniper_winwin_WinAPI_ERROR_HOTKEY_ALREADY_REGISTERED
#define org_unclesniper_winwin_WinAPI_ERROR_HOTKEY_ALREADY_REGISTERED 1409L
#undef org_unclesniper_winwin_WinAPI_ERROR_HOTKEY_NOT_REGISTERED
#define org_unclesniper_winwin_WinAPI_ERROR_HOTKEY_NOT_REGISTERED 1419L
#undef org_unclesniper_winwin_WinAPI_PROCESS_NAME_NATIVE
#define org_unclesniper_winwin_WinAPI_PROCESS_NAME_NATIVE 1L
/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_WinAPI_initNative
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_WinAPI_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    rawErrorMessageFromCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_WinAPI_rawErrorMessageFromCode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    getCurrentThreadId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_WinAPI_getCurrentThreadId
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    getCurrentProcessId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_unclesniper_winwin_WinAPI_getCurrentProcessId
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    _WIN32_WINNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_WinAPI__1WIN32_1WINNT
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    getProcessImageFileNameImpl
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_WinAPI_getProcessImageFileNameImpl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    queryFullProcessImageNameImpl
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_WinAPI_queryFullProcessImageNameImpl
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
