/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_DefWindowProc */

#ifndef _Included_org_unclesniper_winwin_DefWindowProc
#define _Included_org_unclesniper_winwin_DefWindowProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmDestroy
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmDestroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_unclesniper_winwin_DefWindowProc
 * Method:    wmClose
 * Signature: (Lorg/unclesniper/winwin/HWnd;)V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_DefWindowProc_wmClose
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
