/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_WinAPI */

#ifndef _Included_org_unclesniper_winwin_WinAPI
#define _Included_org_unclesniper_winwin_WinAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_unclesniper_winwin_WinAPI_initNative
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_WinAPI_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     org_unclesniper_winwin_WinAPI
 * Method:    rawErrorMessageFromCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_unclesniper_winwin_WinAPI_rawErrorMessageFromCode
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
