/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_unclesniper_winwin_HWnd */

#ifndef _Included_org_unclesniper_winwin_HWnd
#define _Included_org_unclesniper_winwin_HWnd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_unclesniper_winwin_HWnd
 * Method:    closeWindow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_unclesniper_winwin_HWnd_closeWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
